package com.example.konrad.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.konrad.db.Produkt;
import com.example.konrad.db.Zamowienia;

import com.example.konrad.db.ProduktDao;
import com.example.konrad.db.ZamowieniaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig produktDaoConfig;
    private final DaoConfig zamowieniaDaoConfig;

    private final ProduktDao produktDao;
    private final ZamowieniaDao zamowieniaDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        produktDaoConfig = daoConfigMap.get(ProduktDao.class).clone();
        produktDaoConfig.initIdentityScope(type);

        zamowieniaDaoConfig = daoConfigMap.get(ZamowieniaDao.class).clone();
        zamowieniaDaoConfig.initIdentityScope(type);

        produktDao = new ProduktDao(produktDaoConfig, this);
        zamowieniaDao = new ZamowieniaDao(zamowieniaDaoConfig, this);

        registerDao(Produkt.class, produktDao);
        registerDao(Zamowienia.class, zamowieniaDao);
    }
    
    public void clear() {
        produktDaoConfig.clearIdentityScope();
        zamowieniaDaoConfig.clearIdentityScope();
    }

    public ProduktDao getProduktDao() {
        return produktDao;
    }

    public ZamowieniaDao getZamowieniaDao() {
        return zamowieniaDao;
    }

}
