package com.example.konrad.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PRODUKT".
 */
@Entity
public class Produkt {

    @Id(autoincrement = true)
    private Long id;
    private String nazwa;
    private Float cena;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 397793726)
    public Produkt() {
    }

    public Produkt(Long id) {
        this.id = id;
    }

    @Generated(hash = 1291611645)
    public Produkt(Long id, String nazwa, Float cena) {
        this.id = id;
        this.nazwa = nazwa;
        this.cena = cena;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNazwa() {
        return nazwa;
    }

    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }

    public Float getCena() {
        return cena;
    }

    public void setCena(Float cena) {
        this.cena = cena;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
