package com.example.konrad.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PRODUKT".
*/
public class ProduktDao extends AbstractDao<Produkt, Long> {

    public static final String TABLENAME = "PRODUKT";

    /**
     * Properties of entity Produkt.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Nazwa = new Property(1, String.class, "nazwa", false, "NAZWA");
        public final static Property Cena = new Property(2, Float.class, "cena", false, "CENA");
    }


    public ProduktDao(DaoConfig config) {
        super(config);
    }
    
    public ProduktDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PRODUKT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAZWA\" TEXT," + // 1: nazwa
                "\"CENA\" REAL);"); // 2: cena
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PRODUKT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Produkt entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String nazwa = entity.getNazwa();
        if (nazwa != null) {
            stmt.bindString(2, nazwa);
        }
 
        Float cena = entity.getCena();
        if (cena != null) {
            stmt.bindDouble(3, cena);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Produkt entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String nazwa = entity.getNazwa();
        if (nazwa != null) {
            stmt.bindString(2, nazwa);
        }
 
        Float cena = entity.getCena();
        if (cena != null) {
            stmt.bindDouble(3, cena);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Produkt readEntity(Cursor cursor, int offset) {
        Produkt entity = new Produkt( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // nazwa
            cursor.isNull(offset + 2) ? null : cursor.getFloat(offset + 2) // cena
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Produkt entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNazwa(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCena(cursor.isNull(offset + 2) ? null : cursor.getFloat(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Produkt entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Produkt entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Produkt entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
