package com.example.konrad.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ZAMOWIENIA".
 */
@Entity
public class Zamowienia {

    @Id(autoincrement = true)
    private Long id;
    private String Produkt;
    private Float suma;
    private java.util.Date data;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 1186209506)
    public Zamowienia() {
    }

    public Zamowienia(Long id) {
        this.id = id;
    }

    @Generated(hash = 621817571)
    public Zamowienia(Long id, String Produkt, Float suma, java.util.Date data) {
        this.id = id;
        this.Produkt = Produkt;
        this.suma = suma;
        this.data = data;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getProdukt() {
        return Produkt;
    }

    public void setProdukt(String Produkt) {
        this.Produkt = Produkt;
    }

    public Float getSuma() {
        return suma;
    }

    public void setSuma(Float suma) {
        this.suma = suma;
    }

    public java.util.Date getData() {
        return data;
    }

    public void setData(java.util.Date data) {
        this.data = data;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
